[general]
import = ["~/.config/alacritty/rose-pine.toml"]

[window]
opacity = 0.85
padding.x = 10
padding.y = 10

[font]

normal.family = "Ubuntu Mono Nerd Font"
bold.family = "Ubuntu Mono Nerd Font"
italic.family = "Ubuntu Mono Nerd Font"
bold_italic.family = "Ubuntu Mono Nerd Font"

size = 13


[terminal]
shell.program = "/usr/bin/bash"
shell.args = ["-l"]
