# CHANGE DEFAULT KEY
unbind C-b
set -g prefix C-t
set -g repeat-time 400

# SET COLOR TERMINAL
set -g default-terminal "tmux-256color"

# RELOAD FILE
bind r source-file ~/.tmux.conf;

# RENAME AUTO 
set-window-option -g automatic-rename
set-option -wg -g automatic-rename

# COPY AND PASTE LIKE VI
set-window-option -g mode-keys vi
bind p paste-buffer


# MOVE SCREEN LIKE VI
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R


# RESIZE PANE
bind -r C-j resize-pane -D 5
bind -r C-k resize-pane -U 5
bind -r C-h resize-pane -L 5
bind -r C-l resize-pane -R 5


# ACTIVE MOUSE
set -g mouse on
