# CHANGE DEFAULT KEY
unbind C-b
set -g prefix C-t
set -g repeat-time 400

# SET COLOR TERMINAL
set -g default-terminal "tmux-256color"
set -g default-terminal "screen-256color"

set -g history-limit 9999999
unbind -n MouseDrag1Pane

# RELOAD FILE
bind r source-file ~/.tmux.conf;

# RENAME AUTO 
set-window-option -g automatic-rename
set-option -wg -g automatic-rename

# COPY AND PASTE LIKE VI
set-window-option -g mode-keys vi
bind p paste-buffer


# MOVE SCREEN LIKE VI
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R


# RESIZE PANE
bind -r C-j resize-pane -D 5
bind -r C-k resize-pane -U 5
bind -r C-h resize-pane -L 5
bind -r C-l resize-pane -R 5

# ACTIVE MOUSE
set -g mouse on

# Use xclip to copy and paste with the system clipboard
bind C-c run "tmux save-buffer - | xclip -i -sel clip"
bind C-v run "tmux set-buffer $(xclip -o -sel clip); tmux paste-buffer"

# STYLE

# Left side of status bar
set -g status-interval 1
set -g status-left-style "bg=default,fg=colour243"
set -g status-left-length 50
set -g status-left "#[fg=white,bg=brightred,nobold] #S #[fg=brightred,bg=default]"

# Right side of status bar
set -g status-right-style "bg=default,fg=brightred"
set -g status-right-length 150
set -g status-right "#[fg=grey,bg=default]#[fg=black,bg=grey,bold] %H:%M:%S #[fg=blue,bg=blue]#[fg=black,bg=blue] %d-%b-%y #[fg=black,bg=black]"

# Window status
set -g window-status-format "  #I #W  "
set -g window-status-current-format "#[fg=black,bg=orange]#[fg=black,bold] #I #W #[fg=orange,bg=default,bold]"

# Window separator
set -g window-status-separator ""

# Window status alignment
set -g status-justify centre

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

# Other examples:
# set -g @plugin 'github_username/plugin_name'
# set -g @plugin 'github_username/plugin_name#branch'
# set -g @plugin 'git@github.com:user/plugin'
# set -g @plugin 'git@bitbucket.com:user/plugin'
set -g @plugin 'seebi/tmux-colors-solarized' 
set -g @colors-solarized 'dark'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
